### PR TITLE
Fix Issue #386: Add a button so users can reset their AI Profile

### LINKED ISSUE #386: 500 Error when opening AI profile
**Describe the bug**

Some users are getting a 500 error when attempting to open their AI rules.

**To Reproduce**

Open your AI rules.

**Expected behavior**

The user is able to open and change the rules for their AI profile.

**Further Information**

- [ ]  Add a button so users can reset their AI Profile
- [ ]  Find permanent solution to prevent this error from occurring moving forward.

**Screenshots**

Image

Image

### PR DESCRIPTION
**Pull request by Phrosfire**
# Pull Request

Adding a button to allow users to reset their AI profile in the case that their current profile generates the 500 error when attempting to open it.

fix #386 

## License

By making this pull request, I confirm that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the Studie-Tech ApS organization has the copyright to use and modify my contribution for perpetuity.

## Summary by CodeRabbit

- **New Features**
	- Introduced a button in the combat settings to reset the AI profile, enhancing user control over AI behavior.
	- Added error handling with toast messages to inform users of the success or failure of the AI profile reset action.
	- Improved data integrity by filtering out non-existent entries in user-related AI data responses.

### CODE REVIEW

**Comment by MathiasGruber** [comment]
Seems like some stuff is missing from this PR? What's the origin of the 500 error, do we know?

File: app/src/app/profile/edit/page.tsx [hunk 1]
```diff
@@ -445,6 +461,33 @@ const BattleSettingsEdit: React.FC<{ userId: string }> = ({ userId }) => {
...
+                  rules: [
+                    AiRule.parse({
+                      conditions: [ConditionDistanceHigherThan.parse({ value: 2 })],
+                      action: ActionMoveTowardsOpponent.parse({}),
+                    }),
+                  ],
+                  includeDefaultRules: true,
+                };
+            
+                try {
```
Comment (MathiasGruber) [inline app/src/app/profile/edit/page.tsx]: Should not have a try-catch here.. error handling & toases should be within the mutation onSuccess, onError, etc. :) 

I'd suggest we also change the source of the error, which seems to be 

```typescript
options={[
  ...props.userData?.items?.map((ui) => ({
    value: ui.itemId,
    label: ui.item.name,
  })),
  ...props.userData?.jutsus?.map((uj) => ({
    value: uj.jutsuId,
    label: uj.jutsu.name,
  })),
]}
```

I think this will fix it:

```diff
diff --git a/app/src/server/api/routers/profile.ts b/app/src/server/api/routers/profile.ts
index 523a1e52..ea147380 100644
--- a/app/src/server/api/routers/profile.ts
+++ b/app/src/server/api/routers/profile.ts
@@ -413,6 +413,12 @@ export const profileRouter = createTRPCRouter({
         where: and(eq(userData.userId, input.userId), eq(userData.isAi, true)),
         with: { jutsus: { with: { jutsu: true } }, items: { with: { item: true } } },
       });
+      // Filter off entries that do not exist
+      if (user) {
+        user.jutsus = user.jutsus.filter((j) => j.jutsu);
+        user.items = user.items.filter((i) => i.item);
+      }
+      // Return user
       return user ?? null;
     }),
   // Create new AI
@@ -970,6 +976,9 @@ export const profileRouter = createTRPCRouter({
       if (!requester || !canSeeIps(requester.role)) {
         user.lastIp = "hidden";
       }
+      // Filter off entries that do not exist
+      user.jutsus = user.jutsus.filter((j) => j.jutsu);
+      user.items = user.items.filter((i) => i.item);
       // If no avatarLight version, create one
       if (!user.avatarLight && user.avatar) {
         const thumbnail = await createThumbnail(user.avatar);
```

**Review by MathiasGruber — CHANGES_REQUESTED** [review]
I think it's fine to still have a reset button, but let's also fix it at the core :)

File: app/src/app/profile/edit/page.tsx (hunk 1 above)
Comment (Phrosfire) [reply app/src/app/profile/edit/page.tsx]: I have made the changes you proposed and the project successfully builds.  I also added a confirmation for the reset button.

**Review by MathiasGruber — APPROVED** [review]
